Implement /api/embed/:siteId/:pageId
joulev/ezkomment pull request #159
Opened 2022-07-01 14:13 UTC by VietAnh1010

Not too difficult. But this endpoints will depend heavily on the design of the front-end.

A few things to note:
- Comment' date is store as a `Timestamp` object with two fields. What format should it convert it into?
- Fetched comments are not complied from md to html at the moment.

2022-07-01 14:43 UTC, joulev commented
> * Comment's date is store as a `Timestamp` object with two fields. What format should it convert it into?

Let's put it to dd/mm/yyyy hh:mm for now. I suppose it should be trivial to change it later on.

> * Fetched comments are not complied from md to html at the moment.

Why?

> * The current implementation fetchs comments from the API every second or every time a new comment is submitted – which is quite inefficient.

Why? IIRC before this PR, the page only fetches the API in the following occasions:

* When a new comment is submitted
* On page load
* On page focus (so if someone goes away and then goes back, comment is refetched)
* On page visible (if you make the browser the active window again AND the tab is open)

This may look inefficient but it is intended. It is also how the FE as a whole fetches data currently and I do *not* plan to change that.

> * When a new comment is posted, I will sent back the data of that comment, and we just add that comment to render (if it is auto approved). We will need to store the comments in an array (not sure whether this is a good design).

I don't really understand this. Please clarify a bit more.

2022-07-01 14:57 UTC, joulev requested changes
2 out of 4 aren't change requests though.

2022-07-01 14:57 UTC, joulev commented on client/packages/ezkomment.js
> +        console.dir(response, { depth: null });
This one will be logged to client console, which is not good. Remove this.

2022-07-01 14:57 UTC, joulev commented on client/lib/generateCommentHTML.ts
>  import { JSDOM } from "jsdom";
Feel free to move this file to `/server` if you feel like doing so.

2022-07-01 15:18 UTC, VietAnh1010 commented
> Fetched comments are not complied from md to html at the moment.

Because I had not added not it. I wrote it down to not forget it later (I should use checkbox here).

> The current implementation fetchs comments from the API every second or every time a new comment is submitted – which is quite inefficient.

Inspect the console, the comments is fetched quite frequently? Maybe `Alt + Tab` trigger the request? I need to test this more.

> When a new comment is posted, I will sent back the data of that comment, and we just add that comment to render (if it is auto approved). We will need to store the comments in an array (not sure whether this is a good design).

We will leave this to discuss later. It is not very important right now.

2022-07-01 15:19 UTC, VietAnh1010 commented on client/packages/ezkomment.js
> +        console.dir(response, { depth: null });
Don't worry I added this to see why `[object Object]` appears. Will remove this.

2022-07-01 16:23 UTC, joulev commented
> Inspect the console, the comments is fetched quite frequently? Maybe Alt + Tab trigger the request? I need to test this more.


Correct. Alt+tab changes the window, so it is triggered under “on page visible”. This is intentional; I sacrificed API load for user experience here.

2022-07-01 17:18 UTC, VietAnh1010 commented on client/packages/ezkomment.js
> +             * I think I will process the data on the server
Done.

2022-07-02 01:43 UTC, joulev requested changes

2022-07-02 01:43 UTC, joulev commented on client/packages/ezkomment.js
> +        const comments = response.data;
```js
const comments = await fetch(getURL).then(res => res.json()).then(res => res.data);
const comments = (await fetch(getURL).then(res => res.json())).data;
const { data: comments } = await fetch(getURL).then(res => res.json());
```

2022-07-02 01:43 UTC, joulev commented on client/packages/ezkomment.js
> +    let commentDivContent = "";
I intentionally use all-cap here, since this variable is only supposed to be updated _once_.

2022-07-02 01:43 UTC, joulev commented on pages/api/pages/[pageId]/comments.ts
> + * We will protect this route to only allow requests from "/api/embed/*"
I don't think this is even possible. Anyway this is not necessary.

2022-07-02 01:43 UTC, joulev commented on pages/app/site/[siteName]/[pageId]/index.tsx
> +            title={new Date(comment.date).toISOString()}
Q: What is the difference? [Documentation of `Timestamp.toDate()`](https://firebase.google.com/docs/reference/js/firestore_.timestamp.md#timestamptodate)

2022-07-02 01:43 UTC, joulev commented on server/handlers/pageHandlers.ts
> +import { Timestamp } from "firebase-admin/firestore";
Unused import.

2022-07-02 01:43 UTC, joulev commented on server/handlers/pageHandlers.ts
> +        })
Could be a little bit more concise with

```js
rawData.map(async ({ text, ...rest }) => ({ text: await md2html(text), ...rest }));
```

2022-07-02 01:43 UTC, joulev commented on server/utils/crud/commentUtils.ts
> +                date: Timestamp.now().toMillis(),
I also see [`Timestamp.toMillis()`](https://firebase.google.com/docs/reference/js/firestore_.timestamp.md#timestamptomillis) in the documentation.

2022-07-02 01:43 UTC, joulev commented on server/utils/crud/commentUtils.ts
> +            console.dir(newComment, { depth: null });
Remove this (or guard it with a `process.env.NODE_ENV` check). Although this is printed to the server, I think we should still disable all `console.*` in production deployments.

2022-07-02 01:43 UTC, joulev commented on server/utils/crud/pageUtils.ts
> +         * Should the user see the raw comment?
A: For the embedded page, no they shouldn't. However for the public API, yes.

2022-07-02 10:00 UTC, VietAnh1010 commented on client/packages/ezkomment.js
> +    let commentDivContent = "";
Hmm, okay. I will just leave it as all-cap.

2022-07-02 10:02 UTC, VietAnh1010 commented on pages/api/pages/[pageId]/comments.ts
> + * We will protect this route to only allow requests from "/api/embed/*"
Okay

2022-07-02 12:58 UTC, VietAnh1010 commented on pages/app/site/[siteName]/[pageId]/index.tsx
> +            title={new Date(comment.date).toISOString()}
With the old implementation, I store comments' dates as `Timestamp`.

But there is no way to restore it as a `Timestamp` when I read the document, and when I send the document back as JSON.

So I decided to store the date in milliseconds, and afterward, decode it using `new Date()`.

2022-07-02 13:00 UTC, VietAnh1010 commented on server/handlers/pageHandlers.ts
> +        })
Noted. Will change this.

2022-07-02 13:01 UTC, VietAnh1010 commented on server/utils/crud/commentUtils.ts
> +            console.dir(newComment, { depth: null });
I forgot to put the guard clause, will add it.

2022-07-02 13:03 UTC, VietAnh1010 commented on server/utils/crud/pageUtils.ts
> +         * Should the user see the raw comment?
Hmm, this is used to fetch comments for `/app/.../[siteName]/[pageId]`. I wonder whether we should compile the comments for that page?

Probably yes.

2022-07-02 13:06 UTC, joulev commented on pages/app/site/[siteName]/[pageId]/index.tsx
> +            title={new Date(comment.date).toISOString()}
No, I’m asking what is the difference between `Timestamp.toDate()` and `new Date(Timestamp)`. To me they are identical; both giving type `Date`, so there are no reasons to substitute them.

2022-07-02 13:09 UTC, joulev commented on server/utils/crud/pageUtils.ts
> +         * Should the user see the raw comment?
Basically we compile to Markdown before sending to client in all cases except in the public API.

2022-07-02 13:19 UTC, joulev commented on pages/app/site/[siteName]/[pageId]/index.tsx
> +            title={new Date(comment.date).toISOString()}
Ah never mind, I didn’t really think about type change of `comment.date`. This thread is resolved

2022-07-02 13:19 UTC, VietAnh1010 commented on pages/app/site/[siteName]/[pageId]/index.tsx
> +            title={new Date(comment.date).toISOString()}
`Timestamp.toDate()` does not work. Because we have to construct the `Timestamp` object from the JSON response.

2022-07-02 13:24 UTC, VietAnh1010 commented on server/utils/crud/pageUtils.ts
> +         * Should the user see the raw comment?
Okay

2022-07-02 13:49 UTC, VietAnh1010 commented
![image](https://user-images.githubusercontent.com/91171052/177003611-b0078a50-0a18-4bd3-9144-15eb0c85dbce.png)

@joulev Can you resolve this?

2022-07-02 13:55 UTC, joulev commented
> ![image](https://user-images.githubusercontent.com/91171052/177003611-b0078a50-0a18-4bd3-9144-15eb0c85dbce.png)
> 
> 
> 
> @joulev Can you resolve this?

I'm travelling right now so can't do it yet. Will do it on Monday, it's not too hard. For now this is enough (we don't merge this to prod yet so don't worry).

2022-07-02 13:57 UTC, VietAnh1010 commented
Okay. I shall merge this to `main`.

... After I refractor my code. My code looks like spaghetti right now.

I will convert the problem into an issue.

2022-07-02 14:00 UTC, joulev approved these changes

2022-07-02 14:20 UTC, merged